apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodeinfos.cseelye.github.io
spec:
  group: cseelye.github.io
  names:
    kind: NodeInfo
    listKind: NodeInfoList
    plural: nodeinfos
    singular: nodeinfo
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              hostname:
                type: string
              managementIP:
                type: string
              cpuCoreCount:
                type: integer
              memoryBytes:
                type: integer
    served: true
    storage: true
